
package com.quantiguous.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ASBAServiceHttpService", targetNamespace = "http://www.quantiguous.com/services", wsdlLocation = "file:/Users/akhileshkataria/Code/asba_java/ASBAService.wsdl")
public class ASBAServiceHttpService
    extends Service
{

    private final static URL ASBASERVICEHTTPSERVICE_WSDL_LOCATION;
    private final static WebServiceException ASBASERVICEHTTPSERVICE_EXCEPTION;
    private final static QName ASBASERVICEHTTPSERVICE_QNAME = new QName("http://www.quantiguous.com/services", "ASBAServiceHttpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/akhileshkataria/Code/asba_java/ASBAService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ASBASERVICEHTTPSERVICE_WSDL_LOCATION = url;
        ASBASERVICEHTTPSERVICE_EXCEPTION = e;
    }

    public ASBAServiceHttpService() {
        super(__getWsdlLocation(), ASBASERVICEHTTPSERVICE_QNAME);
    }

    public ASBAServiceHttpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ASBASERVICEHTTPSERVICE_QNAME, features);
    }

    public ASBAServiceHttpService(URL wsdlLocation) {
        super(wsdlLocation, ASBASERVICEHTTPSERVICE_QNAME);
    }

    public ASBAServiceHttpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ASBASERVICEHTTPSERVICE_QNAME, features);
    }

    public ASBAServiceHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ASBAServiceHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ASBAService
     */
    @WebEndpoint(name = "ASBAServiceHttpPort")
    public ASBAService getASBAServiceHttpPort() {
        return super.getPort(new QName("http://www.quantiguous.com/services", "ASBAServiceHttpPort"), ASBAService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ASBAService
     */
    @WebEndpoint(name = "ASBAServiceHttpPort")
    public ASBAService getASBAServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.quantiguous.com/services", "ASBAServiceHttpPort"), ASBAService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ASBASERVICEHTTPSERVICE_EXCEPTION!= null) {
            throw ASBASERVICEHTTPSERVICE_EXCEPTION;
        }
        return ASBASERVICEHTTPSERVICE_WSDL_LOCATION;
    }

}
